### ISSUE TITLE
Package is out of date

### ISSUE THREAD

**Issue by myurieff** [AndyQ/NFCPassportReader#1]
Hello. 

I'm getting this error when trying to build the project:

`
Showing Recent Messages
: the Package.resolved file is most likely severely out-of-date and is preventing correct resolution; delete the resolved file and try again
`

Any ideas? Thanks.

**Comment by AndyQ** [comment]
Check what version of Xcode you are running. You need to be on Beta 2. 

I've had reports of this happening when on Beta 1.

**Comment by dshepherd** [comment]
I get the same error on Beta 2 (build 11M337n)

**Comment by AndyQ** [comment]
Interesting - I  checked out the project to a clean folder and built with no issues.  Suspect its just a beta bug.  Closing for now as not sure what I can do about this but will keep an eye out!

**Comment by eldewy** [comment]
I also run the same issue. 
I run it on XCode 11.0 Beta 2 and MacOS Catalina 10.15 Beta
I manually went in my xcodeproj - file and deleted the Package.resolved file. When I rebuild it it creates the file newly but the same error occurs. 
I'm super curious to try out your project and would be happy if we could resolve this issue together.

**Comment by AndyQ** [comment]
You could try removing the included NFCPassportReader override item (From the top of the project).

Then, select File menu - Swift Packages - Resolve Package Versions.
That will then resolve the remote package to the latest current version.
Once that works (do a clean and rebuild) then you re good to go.

If you want, you can then re-drag in the NFCPassportReader folder back into the project so you can edit the package code.
