### ISSUE TITLE
Passports/IDs without photo

### ISSUE THREAD

**Issue by brkerturk** [AndyQ/NFCPassportReader#102]
Hi, 

I was trying to scan an id card without any photo and noticed that the app crashes if there is no photo in the passport/id. This is a common situation in my country as people under 18 is not required to have a photo on their id cards.

I found the code that caused this crash and fixed it in my local package, you can reach me for further details.

Thanks

**Comment by seniyye** [comment]
Hi,

I am also having the same problem. @brkerturk   How did you manage to solve this? Could you please share your solution?

Thanks

**Comment by AndyQ** [comment]
Please raise a PR for this if you would be happy sharing your fix!
