### ISSUE TITLE
I got issue with XCode 12.3

### ISSUE THREAD

**Issue by coffteam2020** [AndyQ/NFCPassportReader#103]
Undefined symbol: enum case for (extension in Foundation):__C.NSScanner.NumberRepresentation.decimal((extension in Foundation):__C.NSScanner.NumberRepresentation.Type) -> (extension in Foundation):__C.NSScanner.NumberRepresentation

Undefined symbol: type metadata accessor for (extension in Foundation):__C.NSScanner.NumberRepresentation

Undefined symbol: (extension in Foundation):__C.NSScanner.scanInt(representation: (extension in Foundation):__C.NSScanner.NumberRepresentation) -> Swift.Int?

Undefined symbol: (extension in Foundation):__C.NSScanner.scanUpToCharacters(from: Foundation.CharacterSet) -> Swift.String?

Undefined symbol: nominal type descriptor for (extension in Foundation):__C.NSNotificationCenter.Publisher

Undefined symbol: protocol conformance descriptor for (extension in Foundation):__C.NSNotificationCenter.Publisher : Combine.Publisher in Foundation

Undefined symbol: type metadata accessor for (extension in Foundation):__C.NSNotificationCenter.Publisher

Undefined symbol: (extension in Foundation):__C.NSNotificationCenter.publisher(for: __C.NSNotificationName, object: Swift.AnyObject?) -> (extension in Foundation):__C.NSNotificationCenter.Publisher

Thank for this project. Could you help me out? @AndyQ @WooD1k @ruudk @danydev @ChristianNorbertBraun

**Comment by sbycrosz** [comment]
Hi @coffteam2020, did you manage to figure this out?

**Comment by AndyQ** [comment]
Do you have any more information as to where you see this?  I've not seen this.

**Comment by sbycrosz** [comment]
Hi, 

In our case, we found out that this is caused by an incompatible swift version

Removing  `"\"$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)\"",` from `LIBRARY_SEARCH_PATHS` would fix the compilation issue

- Sam
