### ISSUE TITLE
Crash on DG7 (signature)

### ISSUE THREAD

**Issue by Benny-iPhone** [AndyQ/NFCPassportReader#108]
## Crash in `getNextTag()` method
- on line `if binToHex(data[pos]) & 0x0F == 0x0F {`
- with message `Swift/ContiguousArrayBuffer.swift:580: Fatal error: Index out of range`
- invoked from: `DataGroup7.parse(_:)`
- with data: `[103,3,2,1,0]`

## Reproduce scenario
Parse data of an Israeli passport of a child.

## Fix Suggestion

Add the next code in `getNextTag()` method:

```
guard data.count > pos else {
      throw NFCPassportReaderError.TagNotValid
}
```

**Comment by AndyQ** [comment]
Should be fixed in 1.1.6
