### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by alv-ti8m** [AndyQ/NFCPassportReader#112]
Hi @AndyQ 
I saw in the source files that there are some logs printing directly using the "print" function instead of your Logging utility.
Could you update them?

Also, right now there's no way to fully disable logs. For my project, I created a LogLevel none=5 to fully disable them.
Don't you think could make sense to add also this possibility?

Thanks and cheers

**Comment by AndyQ** [comment]
Hi - yes I spotted them and they have been removed in next version 1.1.6.

I'll also look at turning off all logs too.

Thanks!
