### ISSUE TITLE
Handle Error Code 203 "System resource unavailable"

### ISSUE THREAD

**Issue by danSamSet** [AndyQ/NFCPassportReader#114]
I'm trying use your framework to read Passport by BAC. But something I figure out some log "error:Error Domain=NFCError Code=203 "System resource unavailable".
I have tried to debug at tagReaderSession(_ session: NFCTagReaderSession, didDetect tags: [NFCTag]) but it hasn't happened. 
Can you give me some advices to detect or handle this error? Thanks.

**Comment by AndyQ** [comment]
What version of iOS are you running?  This was an issue on some iOS 14 versions - does this thread help at all?
https://developer.apple.com/forums/thread/655604
