### ISSUE TITLE
Error reading tag: sw1 - 0x6A, sw2 - 0x86. when scan idcard

### ISSUE THREAD

**Issue by enaifuose** [AndyQ/NFCPassportReader#116]
Hi,

first, i want to thank u for the great work you do.

i m trying to test the NFC scan in id card. but i get the following errors : 

[CoreNFC] 00000002 827685a0 -[NFCTagReaderSession setAlertMessage:]:90  (null)
Error reading tag: sw1 - 0x6A, sw2 - 0x86
reason: Incorrect parameters P1-P2
Re-selecting eMRTD Application
Starting Basic Access Control (BAC)
BACHandler - deriving Document Basic Access Keys
BACHandler - Getting initial challenge
Error reading tag: sw1 - 0x6D, sw2 - 0x00
reason: Instruction code not supported or invalid
ERROR - Instruction code not supported or invalid
BAC Failed

Any help please.

**Comment by danydev** [comment]
When reporting issues it's kind of useful to specify type (id card, passport, etc..) and country of the document you are using

**Comment by shakhzodiosdev** [comment]
The same issue while reading driving license. Have you solved?

**Comment by shakhzodiosdev** [comment]
@enaifuose Any solutions?

**Comment by RobinFarmer** [comment]
Ran into the same problem using a Latvian ID card.

@shakhzodiosdev did you happen to find a solution for this?

**Comment by shakhzodiosdev** [comment]
As I remember you should try to add ISO7816 application identifiers for NFC Tag Reader Session in your plist :
<img width="685" alt="image" src="https://user-images.githubusercontent.com/47933552/182850676-f050d3db-3e31-43dc-b300-9e7e44ba0bd2.png">

your plist should look like that ) I am not sure that it will help you but anyway you can try )

**Comment by RobinFarmer** [comment]
Thanks just tried it but unfortunately the problem remains. 

I did already have the the following:

```
A0000002471001
A0000002472001
```

I added the ones you said but yea same problem.

**Comment by shakhzodiosdev** [comment]
@RobinFarmer These identifiers I found from different sources) I am sure that some of them I do not need also) I just tried to add each identifier that I could find while searching.

**Comment by shakhzodiosdev** [comment]
@RobinFarmer I am sorry earlier I had said the same problem with driving license. Actually I could not solve the issue with driving license and as I remember I had not problem with reading from ID card.

**Comment by RobinFarmer** [comment]
@shakhzodiosdev Thanks,


I did find https://www.eftlab.com/knowledge-base/211-emv-aid-rid-pix/ which has lots of identifiers including:
<img width="1377" alt="Screenshot 2022-08-04 at 15 22 20" src="https://user-images.githubusercontent.com/80266735/182857579-8c28b01e-57e2-4cbe-85ba-f97b825e247e.png">

I can't it to work yet but will continue to look into it.

**Comment by AndyQ** [comment]
I'm closing this as whilst ID cards may work, its not something I can test as I don' have access to any.

If you are able to to get more information, please submit a PR or a new issue with more details
