### ISSUE TITLE
Add NFCPassportReader to .podspect library in pod lib

### ISSUE THREAD

**Issue by olmosbek** [AndyQ/NFCPassportReader#118]
Hello friends. I want to add NFCPassportReader to my own pod fremwork.  I try like that -> s.dependency 'NFCPassportReader', '~> 1.1.6' and  s.dependency 'NFCPassportReader', :git => 'https://github.com/AndyQ/NFCPassportReader', '~> 1.1.6' .. but pod install dont work.  terminal return error ->  CocoaPods could not find compatible versions for pod "NFCPassportReader":
  In Podfile.  how can I add NFCPassportReader framework to my library. Thanks for your help.

**Comment by AndyQ** [comment]
Closing as no update
