### ISSUE TITLE
Please update sample for iOS 13 beta 8

### ISSUE THREAD

**Issue by hoangbossemo** [AndyQ/NFCPassportReader#12]
Please update sample for iOS 13 beta 8, Some classes are deprecated on iOS 13 beta 8

**Comment by SaliienkoAleksandr** [comment]
After update doesn't work scan passport button on iOS 13 beta 8

**Comment by AndyQ** [comment]
Can't replicate this - Sample app is working fine on iOS 13 Beta 8 and 9. Please can you let me know more detail on what your error is?

**Comment by hoangbossemo** [comment]
I checked older version. Now it's working fine on newest iOS 13. Thanks.
