### ISSUE TITLE
Implementation of extract.py for Swift?

### ISSUE THREAD

**Issue by arturocalvoacn** [AndyQ/NFCPassportReader#120]
Has anyone managed to implement the Python script that transforms the masterlist ML file into a PEM file? Or knows how to run it on-device?

**Comment by AndyQ** [comment]
You could do it by manually converting the openssl application calls over to Swift (Which is what I did mostly for the passport reading bits).  Its pretty time consuming to do  but you may well find I've already done a fair bit of bit s you'd need - its just putting it together.

The main reason I didn't do it though is that  automating the master list download is against the  ICAO T&Cs.

I probably won't be doing this but would be happy to incorporate a PR.
