### ISSUE TITLE
Support build for iOS10

### ISSUE THREAD

**Issue by blyscuit** [AndyQ/NFCPassportReader#121]
Currently it's possible to support build for iOS10 by setting `spec.ios.deployment_target = "10.0"` in `NFCPassportReader.podspec` instead of 13.0.

The library will compile just fine with all the `@avaialbe` tag.

**Comment by danydev** [comment]
Support for NFC 7816 starts from iOS 13 https://developer.apple.com/documentation/corenfc/nfciso7816tag

**Comment by AndyQ** [comment]
I won't be adding support for this sorry.
