### ISSUE TITLE
crashed com.apple.core nfc.reader session.delegate

### ISSUE THREAD

**Issue by simpleasy41** [AndyQ/NFCPassportReader#122]
Thank you for the library.
I am getting this error, what should I do? 

![image](https://user-images.githubusercontent.com/93196041/138868059-fda44350-ffd7-416d-a900-b8558f05b13f.png)

**Comment by AndyQ** [comment]
Unfortunately without more information I couldn't possibly guess.  If you are able to get logs or more detailed error information then please re-raise an incident the specific error.
