### ISSUE TITLE
Active Authentication with ECDSA signature not working

### ISSUE THREAD

**Issue by pauphi** [AndyQ/NFCPassportReader#125]
Hi! 

I've noticed that Active Authentication with ECDSA signature does not work. Have tested on documents with both `ecdsa-plain-SHA224` and `ecdsa-plain-SHA384`. The logs are not very helpful, just displaying `Error verifying Active Authentication ECDSA signature`. Active Authentication with RSA signature works as expected.

If I'm not mistaken it's not a huge problem as most documents either support Chip Authentication as well, or use Active Authentication with RSA signature - however, I've seen specimen from Japan that **only** have Active Authentication w/ ECDSA. 

`nRes = EVP_DigestVerifyFinal(ctx, fixedSignature, fixedSignature.count);` in `OpenSSLUtils.verifySignature` returns **0**

**Comment by pauphi** [comment]
Opened a pull request: #129

**Comment by AndyQ** [comment]
Thanks I'll get this added for the next release!

**Comment by AndyQ** [comment]
Merged and in 1.1.9 - thanks!
