### ISSUE TITLE
Module 'NFCPassportReader' was not compiled with library evolution support; using it means binary compatibility for 'XyzFramework' can't be guaranteed

### ISSUE THREAD

**Issue by zaidahmed2468** [AndyQ/NFCPassportReader#126]
I'm making custom framework, When I import my framework file then on press scan nfc passport button nothing will happen.
And the above warning i got in my sdk code.

**Comment by AndyQ** [comment]
Sorry, not sure I can help here without more details.

If you are still having an issue with this please raise a new issue with more information.
