### ISSUE TITLE
dyld: Symbol not found:

### ISSUE THREAD

**Issue by zaidahmed2468** [AndyQ/NFCPassportReader#127]
I'm making custom framework, I import my framework file and run my project then i got this error.
**Error:**
dyld: Symbol not found: _$s17NFCPassportReader21NFCViewDisplayMessageO22requestPresentPassportyA2CmFWC
  Referenced from: /private/var/containers/Bundle/Application/FA7D9C77-4532-4F1E-90B9-5D733AEED701/XYZ Demo.app/Frameworks/XYZ.framework/XYZ
  Expected in: /private/var/containers/Bundle/Application/FA7D9C77-4532-4F1E-90B9-5D733AEED701/XYZ Demo.app/Frameworks/NFCPassportReader.framework/NFCPassportReader
 in /private/var/containers/Bundle/Application/FA7D9C77-4532-4F1E-90B9-5D733AEED701/XYZ Demo.app/Frameworks/XYZ.framework/XYZ
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib:/usr/lib/libMTLCapture.dylib

**Comment by AndyQ** [comment]
Sorry, not sure I can help here without more details.

If you are still having an issue with this please raise a new issue with more information.
