### ISSUE TITLE
Python script not working

### ISSUE THREAD

**Issue by rurouniKaung** [AndyQ/NFCPassportReader#13]
_Originally posted by @falsharabati in https://github.com/AndyQ/NFCPassportReader/issues/7#issuecomment-509933943_
<img width="826" alt="Screenshot 2019-08-27 at 9 43 15 AM" src="https://user-images.githubusercontent.com/42795720/63734509-23fb1400-c8af-11e9-8277-339f306ce03e.png">

**Comment by AndyQ** [comment]
This is most probably because you are using the version of OpenSSL that comes with OS X.

This version doesn't support the cms command. You would need to get a different version of OpenSSL that supports this (e.g via Homebrew)
