### ISSUE TITLE
Issue in Custom Library 

### ISSUE THREAD

**Issue by zaidahmed2468** [AndyQ/NFCPassportReader#134]
I have created my custom framework , there the lib NFCPassportReader working fine but when I import my framework file in my demo project then I got this error. Also I have installed NFCPassportReader in my demo project. 
dyld: Symbol not found: _$s17NFCPassportReader21NFCViewDisplayMessageO22requestPresentPassportyA2CmFWC
  Referenced from: /private/var/containers/Bundle/Application/BE702C33-1564-456F-8308-F30286B91D8F/ShuftiPro Demo.app/Frameworks/ShuftiPro.framework/ShuftiPro
  Expected in: /private/var/containers/Bundle/Application/BE702C33-1564-456F-8308-F30286B91D8F/ShuftiPro Demo.app/Frameworks/NFCPassportReader.framework/NFCPassportReader

**Comment by AndyQ** [comment]
Sorry, not sure I can help here without more details.

If you are still having an issue with this please raise a new issue with more information.
