### ISSUE TITLE
swift build fails with `error: no such module 'CommonCrypto'`

### ISSUE THREAD

**Issue by alevesely** [AndyQ/NFCPassportReader#135]
```
ale@pcale:~/NFCPassportReader$ swift build
Fetching https://github.com/krzyzanowskim/OpenSSL.git
[6279/6279] Fetching objects
Fetched https://github.com/krzyzanowskim/OpenSSL.git (39.91s)
Computing version for https://github.com/krzyzanowskim/OpenSSL.git
Computed https://github.com/krzyzanowskim/OpenSSL.git at 1.1.1400 (0.21s)
Creating working copy for https://github.com/krzyzanowskim/OpenSSL.git
Working copy of https://github.com/krzyzanowskim/OpenSSL.git resolved at 1.1.1400
Building for debugging...
/home/ale/NFCPassportReader /Sources/NFCPassportReader/AES_3DES_DESEncryption.swift:10:8: error: no such module 'CommonCrypto'
import CommonCrypto
       ^
/home/ale/NFCPassportReader /Sources/NFCPassportReader/AES_3DES_DESEncryption.swift:10:8: error: no such module 'CommonCrypto'
import CommonCrypto
       ^
...
```

**Comment by AndyQ** [comment]
➜  NFCPassportReader git:(main) ✗ swift --version
swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
Target: arm64-apple-macosx13.0

➜  NFCPassportReader git:(main) ✗ swift build
Updating https://github.com/krzyzanowskim/OpenSSL.git
Updated https://github.com/krzyzanowskim/OpenSSL.git (7.32s)
Computing version for https://github.com/krzyzanowskim/OpenSSL.git
Computed https://github.com/krzyzanowskim/OpenSSL.git at 1.1.1900 (0.02s)
Working copy of https://github.com/krzyzanowskim/OpenSSL.git resolved at 1.1.1900
Building for debugging...
[39/39] Compiling NFCPassportReader SimpleASN1DumpParser.swift
Build complete! (16.44s)
