### ISSUE TITLE
Question: Flutter Support

### ISSUE THREAD

**Issue by sertunc** [AndyQ/NFCPassportReader#155]
Hello, does this library have a known flutter support? thank you.

**Comment by smlu** [comment]
I've been working on flutter library for biometric passports you can try out: [https://github.com/ZeroPass/dmrtd](https://github.com/ZeroPass/dmrtd)
Tho not everything is implemented yet, but if your passport supports BAC proto you can read all public DG files from passport in raw format except for EF.DG1 and do AA with this library. .

**Comment by sertunc** [comment]
I will review. thank you so much
