### ISSUE TITLE
OpenSSL version issue

### ISSUE THREAD

**Issue by fowwest** [AndyQ/NFCPassportReader#157]
I am using NFCPassportReader via custom native module in my React Native app (v0.69.4) and RN framework involves OpenSSL-universal dependency v1.1.1100 while NFCPassportReader caps it down to v1.1.180 and therefore, it's causing a pod install error as there's a conflict in resolution of OpenSSL-universal pod.
Is it possible to update the podspec of NFCPassportReader to use OpenSSL-universal v1.1.1100?

**Comment by AndyQ** [comment]
There should be no reason why you can't - I've not tested it against that yet, but I'll probably be updating it to use the latest OpenSSL version which I think is currently 1.1.1700

**Comment by harouf** [comment]
Great, could you release a new version with OpenSSL dependency version upgraded to 1.1.1700?

**Comment by AndyQ** [comment]
I've updated to Openssl 1.1.1900 in 2.0.1
