### ISSUE TITLE
First & Last name error

### ISSUE THREAD

**Issue by emirbeytekin** [AndyQ/NFCPassportReader#158]
<img width="389" alt="Ekran Resmi 2022-09-01 13 14 29" src="https://user-images.githubusercontent.com/13369070/187890729-13488380-329d-4565-bb83-48596fe1e7ac.png">
My name and surname appear in the surname field, this problem just occurred

**Comment by brkerturk** [comment]
@emirbeytekin I encountered the same problem. It seems like it is fixed in version 2 (main branch).

**Comment by AndyQ** [comment]
Is this still an issue?

**Comment by danydev** [comment]
pretty sure this has been fixed by https://github.com/AndyQ/NFCPassportReader/commit/d2a659bd4afcbe9ffbae258e6b1f9c3bb8e80bbd
can be closed @AndyQ
