### ISSUE TITLE
Minimum deployment target of iOS 15.0

### ISSUE THREAD

**Issue by emirbeytekin** [AndyQ/NFCPassportReader#161]
Hello,
I'm trying your library with SPM but I have this error:
"Compiling for iOS 13.1, but module 'NFCPassportReader' has a minimum deployment target of iOS 15.0"
Can u check package.swift file please ?

**Comment by AndyQ** [comment]
Sorry, I don't support back prior to iOS 15.  It *may* work for you but I can't confirm this.
