### ISSUE TITLE
pem conversion script is broken

### ISSUE THREAD

**Issue by psvz** [AndyQ/NFCPassportReader#162]
Twice: first, it fails to process .ml file from ICAO - apparently it contains conflicting line.
Secondly, if i rename the file to ldif:

`    (cns,masterLists) = readAndExtractLDIFFile( filename )
  File "C:\Users\snowx\Documents\ns1\pow-voting\implementation\icao-ml-convert.py", line 63, in readAndExtractLDIFFile
    for line in inf:
  File "C:\Users\snowx\miniconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 54: character maps to <undefined>`

Could it be encoding thing?

**Comment by gojogo88** [comment]
+1

**Comment by psvz** [comment]
So, I've gone and done my own parsing: https://github.com/psvz/icao
