### ISSUE TITLE
LDIF format seems changed in new version

### ISSUE THREAD

**Issue by renevdkooi** [AndyQ/NFCPassportReader#177]
In the script it is looking for "CscaMasterListData", but the new file seems to use "pkdMasterListContent"
Maybe add a || line.startswith( "pkdMasterListContent:: "): to the line

Suggestion:

if line.startswith( "cn: "):
                cn = line[4:]
            elif line.startswith( "pkdMasterListContent:: "):
                cert = line[23:]
                adding = True
            elif line.startswith( "CscaMasterListData:: "):
                cert = line[21:]
                adding = True
            elif not line.startswith(" ") and adding == True:
                adding = False
                certs.append( cert )
                cns.append( cn )
                cert = ""
            elif adding == True:
                cert += line

**Comment by AndyQ** [comment]
Will look at fixing this for next release

**Comment by AndyQ** [comment]
This has been fixed in 2.1.0
