### ISSUE TITLE
the extract.py has a problem can not get the pem file

### ISSUE THREAD

**Issue by DYS12345** [AndyQ/NFCPassportReader#191]
the extract.py has a problem can not get the pem file. on 62 line should change to 'elif line.startswith("pkdMasterListContent:: "):'

**Comment by starptit** [comment]
@DYS12345  you can try this PR, i believe it works.
https://github.com/AndyQ/NFCPassportReader/pull/189

**Comment by AndyQ** [comment]
Should be fixed in 2.1.0
