### ISSUE TITLE
Library evolution issue 

### ISSUE THREAD

**Issue by rounaq-jahan** [AndyQ/NFCPassportReader#213]
I am trying to add this package into my sdk and using it into another app but it is giving warning of Library Evolution while I am importing NFCPassportReader and app is not running, can you please look into. It is working fine when I am adding to the app directly though.

**Comment by AndyQ** [comment]
Sorry without more information I have no idea what the issue could be.

**Comment by rounaq-jahan** [comment]
It is probably because of OpenSSL version everything works fine but when I try to import OpennSSL it is throwing this error.

**Comment by AndyQ** [comment]
What version of OpenSSL are you using?

**Comment by rounaq-jahan** [comment]
Anything about 3.0

**Comment by AndyQ** [comment]
Closing this as this is really related to https://github.com/AndyQ/NFCPassportReader/issues/217
