### ISSUE TITLE
readerSession Invalidate Error Handling.

### ISSUE THREAD

**Issue by puneetmahali** [AndyQ/NFCPassportReader#33]
Hi @AndyQ 
I am not getting the invalidate error form the PassportReader class. I need to handle the error when user cancel the session. Something like I need to call 
```
if (readerError.code != .readerSessionInvalidationErrorFirstNDEFTagRead)
            && (readerError.code != .readerSessionInvalidationErrorUserCanceled) { }
```
Can you please let me know how can I access this method so when I cancel the session then display the alert message and on alert button call the session again.

**Comment by AndyQ** [comment]
This should be resolved in 1.0.9 (thanks @danydev for the PR!)
