### ISSUE TITLE
Objective C Support

### ISSUE THREAD

**Issue by jassimkm** [AndyQ/NFCPassportReader#36]
How can I use this in objective-c project

**Comment by danydev** [comment]
More a question for stackoverflow than for the library itself. Usage should not differ from any other use of Swift code from project with objective-c.
https://medium.com/@anum.amin/swift-pod-library-in-objective-c-project-c6d1c5af997d

**Comment by alv-ti8m** [comment]
@danydev @jassimkm  question was actually correct, this framework does not support objective-c. 
You can import, but no methods are marked as @objc. This makes impossible to use on an objective-c project.

Is there any change we can get support for objective-c?

**Comment by AndyQ** [comment]
I'm closing this as I have no plans on supporting Objective-C at this time, and there is a reasonable amount of work to implement this.
