### ISSUE TITLE
mrzKey is wrong for non 9-digits passport numbers

### ISSUE THREAD

**Issue by jkufver** [AndyQ/NFCPassportReader#47]
Hi! I found this issue when trying to debug why not Swedish passports worked with this scanner.

[Sample here](https://www.migrationsverket.se/images/200.5bc6881815e14db67502103/1509103134308/Specimenpass.png)

The problem is this piece of code:

    let mrzKey = "\(passportNumber)\(passportNrChksum)\(dateOfBirth)\(dateOfBirthChksum)\(expiryDate)\(expiryDateChksum)"

The passportNumber must be 9 chars in the key. I solved the problem with this code

    let filler = "<<<<".prefix(max(0, 9 - passportNumber.count))
    let mrzKey = "\(passportNumber)\(filler)\(passportNrChksum)\(dateOfBirth)\(dateOfBirthChksum)\(expiryDate)\(expiryDateChksum)"

I'm very impressed by this framework! Really good piece of work.

Best regards // Jens

**Comment by AndyQ** [comment]
Thanks - this is mentioned in the troubleshooting section - its not something that this framework really can or should handle though - its more the responsibility of the calling application to pass the correct MRZ key in.
