### ISSUE TITLE
Accessing certificate items

### ISSUE THREAD

**Issue by MatthewCochrane-iOS** [AndyQ/NFCPassportReader#51]
How do I retrieve certificate items from the X509Wrapper? Any time I try to retrieve them I am receiving a nil value

**Comment by canssamet** [comment]
> How do I retrieve certificate items from the X509Wrapper? Any time I try to retrieve them I am receiving a nil value
Hi Matthew . Could you access the certificate items?

**Comment by MatthewCochrane-iOS** [comment]
Hi,
Yeah I managed to in the end thank you ☺️

Sent from my iPhone

On 15 May 2020, at 11:37, Can Samet KATKAT <notifications@github.com> wrote:

﻿

How do I retrieve certificate items from the X509Wrapper? Any time I try to retrieve them I am receiving a nil value
Hi Matthew . Could you access the certificate items?

**Comment by canssamet** [comment]
@MatthewCochrane-iOS You misunderstood me.Please help :D If you did it can you explain to me ? How can I access Country Signing Certificate  and  Document Signer Certificate  ?

**Comment by MatthewCochrane-iOS** [comment]
Ahhhhhh, I get you, I haven't download the correct Masterlist pemfile yet, if I do it some time soon and you haven't got it sorted I will let you know! 🙂

________________________________
