### ISSUE TITLE
ld: warning: Could not find auto-linked library

### ISSUE THREAD

**Issue by tricpony** [AndyQ/NFCPassportReader#55]
After flip flopping bitcode build settings all over I finally end up with the link error in the subject.  I can not find the proper build setting to resolve this.  I know it has something to do with OpenSSL having bitcode off, but beyond that, suggestions?  I am trying to deliver the functionality of your pod through my own framework.  It all compiles fine while working directly with the framework, not so much when I try to link that framework to my app.  Tossing the framework is not an option and I would rather not turn it into a pod.

**Comment by AndyQ** [comment]
This may be fixed by moving over to the newly release SPM version of OpenSSL - will be testing that out.

**Comment by AndyQ** [comment]
Closing as I think this should be fixed with SPM support now.  Please open a new issue if required.
