### ISSUE TITLE
Not working in device

### ISSUE THREAD

**Issue by falsharabati** [AndyQ/NFCPassportReader#6]
I'm just trying to run the code, it's working in the simulator but in a real device, it's crash with below log.

`dyld: Symbol not found: _$s7SwiftUI19UIViewRepresentableP13_layoutTraits3forAA07_LayoutF0VSg0C4TypeQz_tFTq
  Referenced from: /var/containers/Bundle/Application/EF99674A-73B5-4DB7-800E-3FDFBA3B32A1/NFCPassportReaderApp.app/NFCPassportReaderApp
  Expected in: /System/Library/Frameworks/SwiftUI.framework/SwiftUI
 in /var/containers/Bundle/Application/EF99674A-73B5-4DB7-800E-3FDFBA3B32A1/NFCPassportReaderApp.app/NFCPassportReaderApp
(lldb) `

<img width="945" alt="Screen Shot 2019-07-09 at 3 38 14 PM" src="https://user-images.githubusercontent.com/48977638/60888522-a7a96480-a25f-11e9-88a2-8d48517b2f90.png">

**Comment by AndyQ** [comment]
What version of iOS are you running - probably only works with latest Beta (Beta 3)

**Comment by falsharabati** [comment]
Yes, I just now upgraded to Beta 3 and its working with me.
thank you

**Comment by falsharabati** [comment]
But i get error
`2019-07-09 20:20:34.887679+0300 NFCPassportReaderApp[314:6517] [AXRuntimeCommon] Unknown client: NFCPassportReaderApp
`

Any advice?

**Comment by AndyQ** [comment]
Doing what and at what point?

**Comment by falsharabati** [comment]
Direct after launch the app

**Comment by AndyQ** [comment]
Sorry unless you have more information (other errors, etc) I have no idea.

**Comment by falsharabati** [comment]
Now its working fine thank you :)

**Comment by anguyen1** [comment]
@falsharabati, 
Hello, I am running into similar issue [AXRuntimeCommon] Unknown client.
Can you please share what you did to address this issue?
Thank you,
Anh

**Comment by dreadrocksean** [comment]
Same here

**Comment by AndyQ** [comment]
Could you paste the full output log when you run the app.
