### ISSUE TITLE
"Unknown error - sw1: 0x63, sw2 - 0xCF ", 99, 207

### ISSUE THREAD

**Issue by brqgoo** [AndyQ/NFCPassportReader#60]
With version 1.0.11 it works well with pretty much all passports. However, I get the following error message when tried with a Chinese passport:
`Sorry, there was a problem reading the passport. ("Unknown error - sw1: 0x63, sw2 - 0xCF ", 99, 207)`

![IMAGE 2020-07-08 12:53:21](https://user-images.githubusercontent.com/64094715/86904913-04ad5400-c11a-11ea-9885-6860465bd007.jpg)

**Comment by AndyQ** [comment]
Not sure what this error means - I think it could possibly be a verify failed - but exactly what - I'm not sure.
Do you have any more detail on what was happening?

**Comment by AndyQ** [comment]
This should be fixed (I hope). If you are still having issues please re-open.

**Comment by advatar** [comment]
@AndyQ What did you change to fix this issue? I am getting it for Argentinian passports and my code is a bit out of sync with master so I need to merge manually.

**Comment by AndyQ** [comment]
I think this was either the change to drop the data read amount down to 0xA0 (160), or possibly the padding around the MRZ Passport number (if its less than 9 chars, it needs to be padded with <)

**Comment by advatar** [comment]
Thanks, I am already doing the padding. Will try 0xa0 as the starting point.

**Comment by advatar** [comment]
@brqgoo Is this working for you now?

**Comment by advatar** [comment]
@AndyQ thanks for the project. I am using much of it for https://svipe.com

**Comment by brqgoo** [comment]
> @brqgoo Is this working for you now?

Unfortunately, I don't have access to a Chinese passport atm. I can give an update when I have a chance to test it.

**Comment by advatar** [comment]
Hmm, I changed to 160 and now have a problem with invalid MRZ

**Comment by advatar** [comment]
I changed to 160 and still get the same problem

![Image from iOS](https://user-images.githubusercontent.com/28670/109537282-0075e280-7abf-11eb-900a-ab077b17bff4.png)

Any ideas what to do next?

**Comment by advatar** [comment]
Turns out that https://github.com/Mattijah/QKMRZParser converts dates to Date with a particular TZ so when computing the MRZ for BAC dates are off by one if you are west of GMT...
