### ISSUE TITLE
Loglevel doesn't work

### ISSUE THREAD

**Issue by ruudk** [AndyQ/NFCPassportReader#63]
The docs talk about an optional `logLevel` param but that doens't seem to work.

https://github.com/AndyQ/NFCPassportReader#logging

**Comment by AndyQ** [comment]
Yes - I've noticed this too - I'll fix this in the next release.

**Comment by hoangnam714** [comment]
<img width="1101" alt="image" src="https://github.com/AndyQ/NFCPassportReader/assets/51524705/ef0652d8-fa6c-4524-8103-c13c56ec9cc0">
i got the same error in demo
