### ISSUE TITLE
Python script not working

### ISSUE THREAD

**Issue by falsharabati** [AndyQ/NFCPassportReader#7]
Can you help me for the below issue, I just download the file in try to extract it.
<img width="637" alt="Screen Shot 2019-07-09 at 8 54 22 PM" src="https://user-images.githubusercontent.com/48977638/60911419-c02f7400-a28b-11e9-8f93-1b2ff2e8d295.png">

**Comment by falsharabati** [comment]
I just run the script from different iMac and it's working fine.

**Comment by rurouniKaung** [comment]
I am having script errors exactly like this even i try to run script on another mac.
