### ISSUE TITLE
Swift Package Manager Error

### ISSUE THREAD

**Issue by brkerturk** [AndyQ/NFCPassportReader#77]
Using spm gives manifest error.

**Comment by AndyQ** [comment]
Yup - this is because it uses OpenSSL which wasn't SPM compatible.

However the OpenSSL Library I am using now has a SPM compatible framework so I'll be testing this out and if works will probably move over to using that going forward.

**Comment by AndyQ** [comment]
Been working on this and with luck, the next release will be SPM compatible
