### ISSUE TITLE
SOD signed data value different from jmrtd 

### ISSUE THREAD

**Issue by jondoe2020** [AndyQ/NFCPassportReader#78]
Hello,
While testing with a malaysian passport I observed that the value(s) returned by both **OpenSSLUtils.extractSignedDataNoVerificationFromPKCS7** and **OpenSSLUtils.verifyAndGetSignedDataFromPKCS7** are both the same (which is not a problem), but different from the value returned by the java jmrtd **SODFile.getEncryptedDigest()** (_https://javadoc.io/doc/org.jmrtd/jmrtd/0.7.9/org/jmrtd/lds/SODFile.html#getEncryptedDigest()_) for the same passport, which I believe is supposed to be the signed content (the java api doc says _Returns the signature (the encrypted digest) over the hashes._)? Is there something I'm missing?

**Comment by AndyQ** [comment]
Yes - thats my bad naming!
Currently, what happens is that I use OpenSSL's CMS code to verify the signed data in the SOD PKCS7 container. This then return the actual data if it is successfully verified. At this point I mark the passport as verified and continue on to do the tampering check (ensure that the datagroup hashes match).

If the verification fails then an error is thrown so the passport is marks as not genuine.  However, I then extract the actual data instead and use it to do the tampering check.

This works fine for most passports BUT is relying on OpenSSL's CMS magic to do stuff.  It also fails if the algorithm used to hash the datagroups is different from that used to hash the message digest of the signed attributes (e.g. one country uses SHA512 for the DG hashes but SHA256 (with RSA) for the messageDigest.

So, I'm currently working on doing the verify part manually (based on RFC 5652 - https://tools.ietf.org/html/rfc5652).  Its working in dev and passed on 7 different nationality passports including one of the above!  

I'll be releasing this soon with the ability to set either between OpenSSL CMS and manual (rfc5652) verification initially but will hopfully move over to the manual verification if that proves better!.
