### ISSUE TITLE
Unreliable behavior on older passports

### ISSUE THREAD

**Issue by g522811** [AndyQ/NFCPassportReader#84]
- A 2015 US passport will consistently scan fine
- A 2007 US passport will have one successful scan out of ~50 attempts
- Tested on iPhone XR and iPhone 8 both running 13.5.1

**Comment by AndyQ** [comment]
Do you have any additional information as to where its failing?
Does it detect the passport and fail whilst reading or is it not even detecting the passport yet?

**Comment by AndyQ** [comment]
Closing due to no update
