### ISSUE TITLE
invalid binary

### ISSUE THREAD

**Issue by zealit** [AndyQ/NFCPassportReader#85]
I implemented this in my app and on the iphone it works well. and if I uploaded to the itunes connect there were no problems, but after reviewing I got Binary invalid, with no reason. Also in testflight it's not possible to install. It stuck and stays grayed out the icon. 

I have target deployment 13.0

**Comment by AndyQ** [comment]
I don't think this is an issue with the passport reader.  If you are sure it is and have some logs then please re-open
