### ISSUE TITLE
not supported blank image

### ISSUE THREAD

**Issue by emirbeytekin** [AndyQ/NFCPassportReader#88]
**my son id card is not have a picture and app is crashed**

**Comment by AndyQ** [comment]
Unfortunately whilst ID cards may work, they are not supported as yet.  You could try only reading specific datagroups (although by default, it should only try to read the data groups that are available).
If you can provide some more detail on what was read or some logs then that would be great.

**Comment by AndyQ** [comment]
Closing as no info - if you can supply some logs or more info that would be great though!
