### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by Shweta25111990** [AndyQ/NFCPassportReader#9]
i am getting below issue:
Showing Recent Messages : the Package.resolved file is most likely severely out-of-date and is preventing correct resolution; delete the resolved file and try

i am running the project on xcode 11 beta 4.Tried downloading XCode 11 beta 2 , but could not succeed.

Could you help me?

**Comment by atullis-scandit** [comment]
This happens when you add a dependency twice. Remove NFCPassportReader from the project navigator and it should work

**Comment by AndyQ** [comment]
Try deleting the included swift package from the project (NOT the one at the bottom of the explorer view but the one at the top), then rescanning the swift dependancies.  That may fix the issue.

**Comment by AndyQ** [comment]
Closing as no more info
