### ISSUE TITLE
OpenSSL 1.1.x support?

### ISSUE THREAD

**Issue by lendvair** [AndyQ/NFCPassportReader#90]
Hi @AndyQ,

Are you planning to use the new OpenSSL-Universal dependency which is updated to OpenSSL 1.1.1i? There are many API breaking changes in this, but the older one (1.0.2) is out of support. 

Best regards,
Richard

**Comment by AndyQ** [comment]
Yes indeed - I'm hoping to start to look at that soon.

**Comment by AndyQ** [comment]
So, I've made a fair bit of progress on this - all the code changes are done and just testing - I'll check in a new branch soon for testing.

I've also made it a Swift Package so it should work with SPM.

It will probably go live with the next release - 1.1.0 - its already got breaking changes in it so this is probably a good time to also upgrade to OpenSSL 1.1

**Comment by AndyQ** [comment]
This is now avavailable in branch 1.1.0 - please test and let me know if any issues!
