### ISSUE TITLE
pod update fails [!] Error installing NFCPassportReader (1.0.17)

### ISSUE THREAD

**Issue by Benny-iPhone** [AndyQ/NFCPassportReader#93]
[!] Error installing NFCPassportReader
[!] /usr/bin/git clone https://github.com/AndyQ/NFCPassportReader.git /var/folders/n0/j55fd2gn0ld0v98nnvkv5z4cm24mns/T/d20210209-9674-xosfv1 --template= --single-branch --depth 1 --branch 1.0.17

Cloning into '/var/folders/n0/j55fd2gn0ld0v98nnvkv5z4cm24mns/T/d20210209-9674-xosfv1'...
warning: Could not find remote branch 1.0.17 to clone.
fatal: Remote branch 1.0.17 not found in upstream origin

**Comment by AndyQ** [comment]
Thanks - fixed - sorry about that!
