### ISSUE TITLE
EVP_DigestVerifyFinal failed, sha224

### ISSUE THREAD

**Issue by wellbranding** [AndyQ/NFCPassportReader#97]
Hello, thanks for providing support for the sha224 [in the following issue](https://github.com/AndyQ/NFCPassportReader/issues/96). I tested one more time, and indeed calcHash no longer fails. However, the SOD verification still fails. Right now the issue is in the **verifySignature** method. It fails at the last part, where **EVP_DigestVerifyFinal** is called. The returned nRes is -1 as you can see in the screenshot.
![image](https://user-images.githubusercontent.com/31806066/111181202-65006980-85b6-11eb-9ed5-1084c3df86d8.png)

Also, I tried to call the verifyPassport method with the useCMSVerification set **as true**. It still did not work, and the error was thrown in the following piece of code:
![image](https://user-images.githubusercontent.com/31806066/111181381-96793500-85b6-11eb-82d3-123eafde505c.png)

Again, if you need any Passport data, I would definitely provide it.
Sincerely, Viktor

**Comment by AndyQ** [comment]
Hi - if you could email me the passport data (address in profile) - export through the sample app) then I'll check it out and see whats going on!

Thanks!

**Comment by AndyQ** [comment]
Thanks for helping identify and test the fix - will be out in the next release

**Comment by AndyQ** [comment]
This should now be fixed in the 1.1.3 release
